version: '3.3'
services:
  # postgres:
  #   image: postgres:12.1-alpine
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5432:5432
  #   volumes: 
  #     - /var/lib/postgresql/data
  #   expose:
  #     - 5432
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes: 
      - /data/db
  web:
    container_name: backend
    build: .
    command: >
      sh -c "yarn
      && yarn dev"
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - '3333:3333'
    # links:
      # - postgres
    depends_on:
      # - postgres
      - mongo
    env_file:
      - .env
